server:
    port: 10001

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sys_user?useAffectedRows=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&&useSSL=false
      username: root
      password: 123456
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: user-server
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379


mybatis:
    # Mybatis配置Mapper路径
    mapper-locations: classpath:mapper/*.xml
    # Mybatis配置Model类对应
    type-aliases-package: com.wang.model.entity

pagehelper:
    params: count=countSql
    # 指定分页插件使用哪种方言
    helper-dialect: mysql
    # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
    reasonable: 'true'
    support-methods-arguments: 'true'

mapper:
    # 通用Mapper的insertSelective和updateByPrimaryKeySelective中是否判断字符串类型!=''
    not-empty: true

# 日志配置
log:
  path: ./logs/check
logging:
  level:
    com:
      fasterxml:
        jackson: INFO
      maxchain:
        east: DEBUG
    org:
      springframework: INFO

jwtKey: passwordskhw
# RefreshToken过期时间-30分钟-30*60(秒为单位)
refreshTokenExpireTime: 1800

